#!/bin/bash

set -x
set -o errexit
set -o nounset
set -o pipefail

action=$CNAB_ACTION

case $action in
    install)
        echo "Installing chart"
        helm install $CNAB_INSTALLATION_NAME mysql/mysql
        ;;
    uninstall)
        echo "Uninstall action"
        echo "not supported yet"
        ;;
    upgrade)
        echo "Upgrade action"
        echo "not supported yet"
        ;;
    status)
        echo "Status action"
        helm status istio
        helm status riff
        ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $CNAB_INSTALLATION_NAME"
