#!/bin/bash

set -x
set -o errexit
set -o nounset
set -o pipefail

action=$CNAB_ACTION
repo_name="stable"

case $action in
    install)
        echo "Initializing helm"
        helm init
        
        echo "Adding repo"
        if [[ $REPO_URL != "stable" ]]; then
          repo_name=$CHART
          helm repo add $CHART $REPO_URL
        fi
        helm repo update

        echo "Installing chart"
        helm install $CNAB_INSTALLATION_NAME $repo_name/$CHART
        ;;
    uninstall)
        echo "Uninstall action"
        echo "not supported yet"
        ;;
    upgrade)
        echo "Upgrade action"
        echo "not supported yet"
        ;;
    status)
        echo "Status action"
        helm status istio
        helm status riff
        ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $CNAB_INSTALLATION_NAME"
